[project]
name = "tarAIntino-datapipeline"
version = "0.1.0"
description = "Data ingestion and preprocessing pipeline for the TarAIntino project."
readme = "../../README.md"
requires-python = ">=3.11"
dependencies = [
    # Core environment
    "numpy==1.26.4",
    "pandas==2.2.3",
    "scikit-learn==1.5.2",
    "scipy==1.13.1",
    "matplotlib==3.8.0",

    # Google Cloud
    "google-cloud-storage==2.18.2",
    "google-auth>=2.35.0",
    "tqdm==4.66.4",

    # Vector DB
    "chromadb"
]

[tool.uv]
virtualenvs.in-project = true
